export const guardedExecutionProof = {
  generatedAt: "2026-07-10T10:05:00.000Z",
  sdk: "@tetherto/wdk",
  walletModule: "@tetherto/wdk-wallet-evm",
  network: "Sepolia",
  chainId: 11155111,
  command: "npm run wdk:policy-demo:json",
  request: {
    id: "request-van-rental",
    title: "120-unit van rental",
    amountUnits: 120,
    tokenSymbol: "MockUSDT",
    approvals: [
      { id: "approval-van-captain", role: "Captain" },
      { id: "approval-van-treasurer", role: "Treasurer" },
    ],
  },
  intent: {
    id: "intent-van-rental",
    hash: "0xae51a8adbc7362a951095786eb18fb4df0475ca15a64c7f7188c20f6d876905d",
    status: "authorized",
    expiresAt: "2026-07-11T08:30:00.000Z",
    nonce: "semi-demo-1",
  },
  safeEphemeralAddress: "0xfC1Cb4E5431Ede87Af7E9b32b5270835912Dd908",
  policyDecisions: [
    {
      scenario: "Insufficient approvals",
      result: "DENY",
      detail: "One Captain approval on a 120-unit request cannot produce a usable capability.",
    },
    {
      scenario: "Exact approved payment",
      result: "ALLOW",
      detail: "WDK native signTransaction simulation matched the exact PaymentIntent.",
    },
    {
      scenario: "Changed recipient",
      result: "DENY",
      detail: "Prepared ERC-20 calldata no longer matched the approved recipient.",
    },
    {
      scenario: "Changed amount",
      result: "DENY",
      detail: "Prepared ERC-20 calldata no longer matched the approved amount.",
    },
    {
      scenario: "Expired intent",
      result: "DENY",
      detail: "Lifecycle and expiry checks block stale capabilities.",
    },
    {
      scenario: "Reused intent",
      result: "DENY",
      detail: "Consumed intents are denied by the same WDK policy lifecycle gate.",
    },
  ],
  feeQuote: {
    estimatedFeeAtomic: "49163406007212",
  },
  executionReceipt: {
    prepared: true,
    signed: true,
    broadcast: false,
    calldataHash:
      "0xb109ce3afb69c3c2f053e450e89dfa383f6c85d32ee66d9368c0426e4a9905c3",
    tokenAddress: "0x0000000000000000000000000000000000002000",
    recipient: "0x0000000000000000000000000000000000003000",
    amountAtomic: "120000000",
  },
  auditJournal: [
    "PaymentIntentCreated",
    "WdkPolicyAllowed",
    "TransactionQuoted",
    "TransactionPrepared",
    "TransactionSigned",
  ],
  disclosures: [
    "The browser visualizes the guarded execution result.",
    "Real WDK native execution runs in Node/CI because WDK depends on native runtime capabilities.",
    "The displayed proof shape is generated by the real WDK policy demo.",
    "Browser payment execution is not claimed.",
    "No transaction was broadcast.",
    "MockUSDT is a test-token label, not official USDt.",
  ],
} as const;
